# Author 1: Liran
# Author 2: Abhishek
# This file contains the chain of runnables that process the user's question and generate the SQL query and results.
from dotenv import load_dotenv
from langchain_core.runnables import RunnableLambda, RunnablePassthrough, RunnableParallel
from apps.langchain_bot.dependencies import document_retriever, llm, database_information_retrieval
from typing import Dict, Any
from langchain_community.tools.sql_database.tool import QuerySQLDataBaseTool
from langchain_core.runnables.utils import AddableDict
import pandas as pd

# Method to retrieve the context containing the top k tables based on the user's query by invoking the semantic search similarity
def get_context(inputs: Dict[str, Any]) -> str:
    """
    Retrieves the top k tables based on the user's query and formats them as a string.

    Args:
        inputs (Dict[str, Any]): A dictionary containing the user's query under the key "question".

    Returns:
        str: A formatted string representation of the top k tables related to the query.
    """
    context = document_retriever.find_top_k_similar(inputs["question"], k=3)
    return context

# Method to create the final prompt using the user's question, context containing top k table information, and guidelines for generating the SQL query
def create_final_prompt(question: str, context: str) -> str:
    final_prompt = f"""
    You are a PostgreSQL expert. Based on the input question, generate a syntactically correct PostgreSQL query that strictly adheres to the following rules:  
    - Return only the generated query, with no additional text.  
    - Remember NOT include backticks ```sql ``` before and after the created query. 

    Context: Use only the table names and column names provided in: {context}. Ensure the query accurately reflects the structure of these tables.  

    Guidelines:  
    1. If the context contains multiple tables, use a `JOIN` operation based on the column `unitid`.  
    2. Avoid querying columns that are not present in the tables.  
    3. Use aliases only when necessary.  
    4. Pay close attention to which columns belong to which table to ensure correctness.  

    User question: {question['question']}
    History Message: {question['messages']}
    """
    output = AddableDict({'question':question['question'], 'messages': question['messages'], 'final_prompt': final_prompt})
    return output

# Method to generate the SQL query after invoke the final prompt using the language model
def generate_sql_llm(inputs: Dict[str, Any]) -> str:
    """
    Generates SQL code using the provided final prompt.

    Args:
        final_prompt (str): The complete prompt including the question and context.

    Returns:
        str: The SQL query generated by the LLM.
    """
    sql_query = llm.invoke(inputs['final_prompt'])
    del inputs['final_prompt']
    del inputs['messages']
    output = inputs + AddableDict({'sql_query': sql_query})
    return output

# Method to excute the SQL query and return the results 
def get_query_results(inputs: Dict[str, Any]) -> Any:
    """
    Executes the provided SQL query and returns the results.

    Args:
        sql_query (str): The SQL query to execute.

    Returns:
        str: The results of the query (mocked as "25 students").
    """
    execute_query = (RunnablePassthrough.assign(
            result=RunnableLambda(lambda x: inputs['sql_query']) | QuerySQLDataBaseTool(db=database_information_retrieval)
        )
    )
    query_results = execute_query.invoke({})
    output = inputs +  AddableDict({'query_results': query_results['result']})
    return output

# Method to rephrase the sql query results using the language model
def rephrase_query_results(inputs: Dict[str, Any]) -> str:
    
    answer_prompt=f"""Given the following user question, corresponding SQL query, and SQL result, provide answer for the user question.
        User Question: {inputs['question']}
        SQL Query: {inputs['sql_query']}
        SQL Result: {inputs['query_results']}
        Answer: """
    return llm.invoke(answer_prompt)


# Wrap functions with RunnableLambda to create runnables that process the input and send the output to the next runnable in the chain
get_context_runnable = RunnableLambda(get_context)
create_final_prompt_runnable = RunnableLambda(lambda inputs: create_final_prompt(**inputs))
generate_sql_llm_runnable = RunnableLambda(generate_sql_llm)
get_query_results_runnable = RunnableLambda(get_query_results)
rephrase_query_results_runnable = RunnableLambda(rephrase_query_results)

# Compose the chain using the pipe operator.
chain = (
        RunnableParallel({
            "context": get_context_runnable,
            "question": RunnablePassthrough(),
        })
        | create_final_prompt_runnable
        | generate_sql_llm_runnable
        | get_query_results_runnable
        | rephrase_query_results_runnable
)

#
# from langchain.schema.runnable import Runnable
#
# class DebugStep(Runnable):
#     def __init__(self, runnable, name):
#         self.runnable = runnable
#         self.name = name
#
#     def invoke(self, input, config=None):
#         print(f"--- {self.name} INPUT ---")
#         print(input)
#         output = self.runnable.invoke(input, config=config)
#         print(f"--- {self.name} OUTPUT ---")
#         print(output)
#
#         # Return both original output and debug trace
#         return {
#             **(input if isinstance(input, dict) else {"input": input}),
#             self.name: output
#         }
#
# if __name__ == "__main__":
#     chain_debug = (
#             RunnableParallel({
#                 "context": DebugStep(get_context_runnable, "get_context_runnable"),
#                 "question": RunnablePassthrough(),
#             })
#             | DebugStep(create_final_prompt_runnable, "create_final_prompt_runnable")
#             | DebugStep(generate_sql_llm_runnable, "generate_sql_llm_runnable")
#             | DebugStep(get_query_results_runnable, "get_query_results_runnable")
#             | DebugStep(rephrase_query_results_runnable, "rephrase_query_results_runnable")
#     )
#
#     df = pd.read_csv("data/test_data/eval_data.csv")
#     for row in df.iterrows():
#         user_question  = row["Human Language"]
#         results = chain_debug.invoke({"question": user_question})
#         print("=== FINAL RESULT ===")
#         print(results)
#         # {
#         #     "question": "Find all users who joined last week",
#         #     "get_context_runnable": "...context output...",
#         #     "create_final_prompt_runnable": "...final prompt...",
#         #     "generate_sql_llm_runnable": "SELECT * FROM users WHERE ...",
#         #     "get_query_results_runnable": "...query results...",
#         #     "rephrase_query_results_runnable": "There are 12 users who joined last week."
#         # }
#
#
#         ## Evaluation Compare
#         ## Ground true vs Predict
#         if row["Table Name ( Main)"] == results["get_context_runnable"]["TABLE_NAME"]:
#             pass
#         if row["Expected SQL Query"] == results["generate_sql_llm_runnable"]:
#             pass
#             ## Calculate Accuracy

# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
#
# def evaluate_classification(y_true, y_pred, average='binary'):
#     """
#     Calculate accuracy, F1 score, recall, and precision.
#
#     Parameters:
#     - y_true: list or array, true labels
#     - y_pred: list or array, predicted labels
#     - average: 'binary', 'micro', 'macro', or 'weighted'
#         Use 'binary' for binary classification, 'macro'/'weighted' for multi-class.
#
#     Returns:
#     - metrics: dict with accuracy, f1, precision, and recall
#     """
#     accuracy = accuracy_score(y_true, y_pred)
#     f1 = f1_score(y_true, y_pred, average=average)
#     precision = precision_score(y_true, y_pred, average=average)
#     recall = recall_score(y_true, y_pred, average=average)
#
#     return {
#         "accuracy": accuracy,
#         "f1_score": f1,
#         "precision": precision,
#         "recall": recall
#     }
#
# # Example usage
# y_true = [0, 1, 1, 1, 0, 1, 0, 0]
# y_pred = [0, 1, 0, 1, 0, 1, 1, 0]
#
# metrics = evaluate_classification(y_true, y_pred)
# print(metrics)




