name: Run Pytest Tests

on:
  pull_request:
    branches:
      - main  # Trigger workflow for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code so the workflow can access it 
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  

      # Download embedding model
      - name: Download embedding model
        run: |
          mkdir -p models/embedding_model
          # Download the embedding model from [Google Drive](https://drive.google.com/drive/folders/1ANo_rGZ_bScGuDaTetj07YjxxFr9CC7G)
          cp -r models/embedding_model/embedding_question2context  

      # Run pytest on test folder and store logs 
      - name: Run Pytest
        run: |
          python test.py > pytest_results.log  || true  

       
      #  Upload test results as artifact
      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: result.log  # Upload test results 

      #  Generate  test report
      - name: Generate test report
        run: |
          pytest tests/ --maxfail=5 --disable-warnings --capture=no > report.txt
          echo "Generated Test Report"
          cat report.txt  # Print report

      #  Upload the detailed test report as artifact
      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.txt  