name: Run Pytest Tests

on: push

  #pull_request:
    #branches:
     # - main  # Trigger workflow for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest   #Git Action runner 

    steps:
      # Checkout the code so the workflow can access it 
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r apps/langchain_bot/requirements.txt 

      # Download embedding model
      - name: Download embedding model
        run: |
          mkdir -p models/embedding_model
          # Download the embedding model from [Google Drive](https://drive.google.com/drive/folders/1ANo_rGZ_bScGuDaTetj07YjxxFr9CC7G)
          cp -r models/embedding_model/embedding_question2context  models/embedding_model

      # Run pytest on test folder and store logs 
      - name: Run Pytest
        run: |
           pytest test/  > pytest_results.log  || true  

       